### ISSUE TITLE
Incorrect pop up

### ISSUE THREAD

**Issue by samratchak** [speedovation/kiwi-doc#1]
When I click on the text box in the bottom left hand corner and then I click on the icon on the extreme bottom left, the first pop up menu disappears and the second one appears. But when I click on a blank space to deselect the pop up menu, the first one reappears. This shouldn’t happen.

**Comment by codeyash** [comment]
Please use https://github.com/speedovation/kiwi for future reporting.

If possible recreate there.

Let me check what is problem.

Thanks for reporting.

**Comment by codeyash** [comment]
This issue was moved to speedovation/kiwi#32
