### ISSUE TITLE
Tag roll over

### ISSUE THREAD

**Issue by samratchak** [speedovation/kiwi-doc#3]
The black boxes on mouse hover of HTML tags, is unreadable. Also they tend to remain in the place even after switching to a different application, unless the other application is selected.

**Comment by codeyash** [comment]
Under dev. These are tooltips. Mostly old skins don't support.

TODO
1. We have to complete its functionality.
2. Add support in all themes

**Comment by codeyash** [comment]
The tool tips vanish just after a split second of showing up. Instead transparent boxes show up.

**Comment by codeyash** [comment]
This issue was moved to speedovation/kiwi#30
